# Generated by Django 3.2.4 on 2022-12-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=30)),
                ('ppic', models.ImageField(null=True, upload_to='static/profile')),
                ('passwd', models.CharField(max_length=60)),
                ('cpasswd', models.CharField(max_length=60)),
                ('address', models.TextField()),
            ],
        ),
    ]
