# Generated by Django 3.2.4 on 2023-01-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=60)),
                ('aadhar', models.CharField(max_length=60)),
                ('pan', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
                ('aphone', models.CharField(max_length=60)),
                ('job', models.CharField(max_length=60)),
                ('date', models.DateField()),
            ],
        ),
    ]
